PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX aat: <http://vocab.getty.edu/aat/>
PREFIX gvp: <http://vocab.getty.edu/ontology#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX aatc: <http://vocabularies.dans.knaw.nl/aatconcepts/>


SELECT  ?concept ?label_literal_en ?label_literal_nl
WHERE
{
    ?concept a gvp:Concept ;
        skos:inScheme aat: ;
        skosxl:prefLabel ?preflabel .
        
    { ?preflabel  dcterms:language aat:300388277 ; skosxl:literalForm ?label_literal_en. }
    UNION
    { ?preflabel  dcterms:language aat:300388256 ; skosxl:literalForm ?label_literal_nl . }
}